# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        runner:
          - os: ubuntu-latest
            env_fail: SampleNativeLibrary.so
            env_pass: SampleNativeLibraryWithLoader.so
          - os: windows-latest
            env_fail: SampleNativeLibrary.dll
            env_pass: SampleNativeLibraryWithLoader.dll
          - os: macos-latest
            env_fail: SampleNativeLibrary.dylib
            env_pass: SampleNativeLibraryWithLoader.dylib
    runs-on: ${{ matrix.runner.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Test Resource
      run: dotnet publish --use-current-runtime
      working-directory: TestResources
    - name: Test (fail)
      id: test-fail
      run: dotnet test --verbosity normal
      continue-on-error: true
      env:
        NATIVE_PLUGIN_NAME: ${{ matrix.runner.env_fail }}
    - name: Test (pass)
      run: dotnet test --verbosity normal
      env:
        NATIVE_PLUGIN_NAME: ${{ matrix.runner.env_pass }}
